services:
  zebrad:
    image: zfnd/zebra
    environment:
    - RPC_PORT=18232
    restart: unless-stopped
    ports:
    # - 18232:18232 # RPC (security sensitive). Don't list this as the litewalletd server can talk to it anyway.
    - 18233:18233 # Zcash network (public)
    healthcheck:
      start_period: 1m
      interval: 15s
      timeout: 10s
      retries: 3
      test: ["CMD-SHELL", "curl --data-binary '{\"jsonrpc\":\"2.0\",\"id\":\"curltest\",\"method\":\"getinfo\",\"params\":[]}' -H 'Content-Type: application/json' http://127.0.0.1:18232 || exit 1"]
    volumes:
    - zcash_testnet_zebrad_cache:/var/cache/zebrad-cache
    - ./zebrad.toml:/etc/zebrad/zebrad.toml
  litewalletd:
    image: electriccoinco/lightwalletd
    depends_on:
      zebrad:
        condition: service_healthy
    command: >
      --grpc-bind-addr 0.0.0.0:19067
      --tls-cert /srv/lightwalletd/conf/fullchain.pem
      --tls-key /srv/lightwalletd/conf/privkey.pem
      --zcash-conf-path /srv/lightwalletd/conf/zcash.conf
      --data-dir /srv/lightwalletd/db_volume
      --log-file /dev/stdout
    restart: unless-stopped
    ports:
    - 19067:19067
    volumes:
    - litewalletd:/srv/lightwalletd/db_volume
    - ./lightwalletd_conf:/srv/lightwalletd/conf
volumes:
  zcash_testnet_zebrad_cache:
    external: true # ensures the volume will never be deleted by docker-compose down
  litewalletd:

